<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateBooksTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::disableForeignKeyConstraints();
        Schema::create('books', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->timestamps();

            $table->string('title')->comment('Book title');
            $table->string('code')->nullable()->comment('Book code; is generated by the system');
            $table->unsignedBigInteger('genre_id')->nullable()->comment('Book genre');
            $table->foreign('genre_id')->references('id')->on('genres')->onUpdate('cascade')->onDelete('cascade');
            $table->string('cover')->nullable()->comment('Book cover url; it is display as file input');
            $table->date('published_at')->nullable()->comment('Book published date');
            $table->integer('edition')->comment('Book edition number');
            $table->timestamp('bought_at')->nullable()->comment('Book bought date and time');
            $table->longtext('resume')->nullable()->comment('Book resume; it is display as rich text input');
            $table->softDeletes();
        });
        Schema::enableForeignKeyConstraints();
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::disableForeignKeyConstraints();
        Schema::dropIfExists('books');
        Schema::enableForeignKeyConstraints();
    }
}
